### ISSUE TITLE
last_upload_* files are sometimes not saved well during a bad event like a crash

### ISSUE THREAD

**Issue by Arkiver2** [ArchiveTeam/NewsGrabber#42]
If the script finds there are problems with one or more of the last_upload_\* files it  should go through the files and fix them if needed.

**Comment by Arkiver2** [comment]
Log:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "main.py", line 183, in upload
    itemsize, itemnum = uploadfile.read().split(',', 1)
ValueError: need more than 1 value to unpack
```

**Comment by Arkiver2** [comment]
These files are not used anymore in the new version of the main scripts.
