### ISSUE TITLE
Rejoin IRC channel if disconnected

### ISSUE THREAD

**Issue by Arkiver2** [ArchiveTeam/NewsGrabber#57]

**Comment by Arkiver2** [comment]
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "main.py", line 197, in upload
    irc_print(irc_channel_bot, name + ' uploaded unsuccessful.')
  File "main.py", line 154, in irc_print
    irc_bot_start()
   File "main.py", line 49, in irc_bot_start
    irc.connect((irc_server, irc_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 106] Transport endpoint is already connected
